name: codacy-coverage

on:
  push:
    branches: [ master, develop, feature-* ]
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Test with Maven
      run: mvn -B test --file pom.xml
    - name: Upload coverage
      uses: codacy/codacy-coverage-reporter-action@master
      with:
        project-token: fb35a1398997420e8f6c7e0da9219b02     
      #run: mvn com.gavinmogan:codacy-maven-plugin:coverage -DcoverageReportFile=target/jacoco-ut/jacoco.xml -DprojectToken=${{ secrets.CODACY_PROJECT_TOKEN }} -DapiToken=${{ secrets.CODACY_API_TOKEN }}
       
      
        
